# Generated by Django 3.1.2 on 2021-03-09 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kite_name', models.CharField(max_length=25)),
                ('kite_category', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Kite_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField()),
                ('available_colors', models.CharField(max_length=100)),
                ('kite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kites', to='myapp.kite')),
            ],
        ),
    ]
